In [40]:
# Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# Files to load
avg_rain_state_data_to_load = os.path.join("~/Desktop/Class Folder/Resources/avg_rain_state_data.csv")

# Read the donor data file and store it in a Pandas DataFrame.
avg_rain_state_data_df = pd.read_csv(avg_rain_state_data_to_load)
avg_rain_state_data_df

,State,Inches,MilliÂ­metres,Rank,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Inches.1
0,Alabama,58.3,1480,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alaska,22.5,572,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arizona,13.6,345,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arkansas,50.6,1284,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,California,22.2,563,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Colorado,15.9,405,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Connecticut,50.3,1279,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Delaware,45.7,1160,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Florida,54.5,1385,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Georgia,50.7,1287,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Hawaii,63.7,1618,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Idaho,18.9,481,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Illinois,39.2,996,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Indiana,41.7,1060,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Iowa,34.0,864,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Kansas,28.9,733,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Kentucky,48.9,1242,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Louisiana,60.1,1528,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Maine,42.2,1072,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Maryland,44.5,1131,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Massachusetts,47.7,1211,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Michigan,32.8,833,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Minnesota,27.3,693,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Mississippi,59.0,1499,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Missouri,42.2,1071,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Montana,15.3,390,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Nebraska,23.6,599,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Nevada,9.5,241,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,New Hampshire,43.4,1103,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,New Jersey,47.1,1196,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,New Mexico,14.6,370,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,New York,41.8,1062,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,North Carolina,50.3,1279,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,North Dakota,17.8,452,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Ohio,39.1,993,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Oklahoma,36.5,927,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Oregon,27.4,695,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Pennsylvania,42.9,1089,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Rhode Island,47.9,1218,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,South Carolina,49.8,1264,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,South Dakota,20.1,511,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Tennessee,54.2,1376,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Texas,28.9,734,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Utah,12.2,310,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Vermont,42.7,1085,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Virginia,44.3,1125,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Washington,38.4,976,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,West Virginia,45.2,1147,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Wisconsin,32.6,829,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Wyoming,12.9,328,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
avg_rain_state_data_df.groupby(['Rank'],sort = True, ascending = True)
avg_rain_state_data_df

TypeError: groupby() got an unexpected keyword argument 'ascending'

In [ ]:
# Create graph
x_axis = np.arange(len(df))
tick_locations = [value for value in x_axis]
plt.figure(figsize=(20,3))

In [ ]:
plt.bar(x_axis, df["Inches"])
plt.xticks(tick_locations, df["State"], rotation = len(df["State"])

In [ ]:
plt.title("Rain in Inches by State")
plt.xlabel("State")
plt.ylabel("Rain (inches)")
plt.show()